[package]
name = "test-macro-namespacing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_reflect = "0.8.0"
reflect-steroids = { path = "../.." }
